server:
  port: 80

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
  file.name: logGateway.txt

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: /
          uri: http://localhost:8081
          predicates:
            - Path=/

        - id: registration
          uri: http://localhost:8081
          predicates:
            - Path=/registration

        - id: login
          uri: http://localhost:8081
          predicates:
            - Path=/login

        - id: card
          uri: http://localhost:8080
          predicates:
            - Path=/card/**
